import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  toggleLanguage: () => void;
  isRTL: boolean;
  t: Record<string, string>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    budgeting: "Initial Estimates",
    timeExpenses: "Actual Expenses",
    payments: "Payments & Cashflow",
    settings: "Settings & Rates",
    totalContractValue: "Total Contract Value",
    approvedFee: "Approved Fee",
    totalBurn: "Actual Cost (AC)",
    includesOverhead: "Includes Overhead",
    remainingBudget: "Remaining Budget",
    prodBudget: "Prod. Budget",
    currentMargin: "Forecast Profit Margin",
    target: "Target",
    budgetStatus: "Budget Consumption Status",
    utilized: "Utilized",
    ofProdBudget: "of Production Budget",
    calcNote: "*Calculated based on Net Revenue minus Target Profit",
    costDist: "Cost Distribution (Riyadh vs Cairo)",
    riyadhMgmt: "Riyadh (Management)",
    cairoProd: "Cairo (Production)",
    extExpenses: "External Expenses",
    criticalAlert: "Critical Alert: Budget Depletion Imminent",
    alertMsg: "You have consumed {pct} of your production budget. Immediate action required.",
    logHours: "Log Hours (Timesheet)",
    staffMember: "Staff Member",
    selectResource: "Select Resource...",
    hoursSpent: "Hours Spent",
    phase: "Phase",
    phaseOther: "Other",
    description: "Description",
    taskDetail: "Task detail...",
    addTimeLog: "Add Time Log",
    logExpenses: "Log Expenses (ODCs)",
    category: "Category",
    amount: "Amount",
    reimbursable: "Reimbursable (Client Pays)",
    addExpense: "Add Expense",
    recentTrans: "Recent Transactions",
    type: "Type",
    costType: "Cost Type",
    action: "Action",
    labor: "Labor",
    expense: "Expense",
    loadedCost: "Loaded Cost",
    directCost: "Direct Cost",
    noEntries: "No entries logged yet.",
    projectParams: "Project Financial Parameters",
    feeNote: "Total fee signed with the client (excluding VAT).",
    overhead: "Overhead Multiplier (OH)",
    overheadNote: "Multiplies base salary to cover rent, admin, etc.",
    targetMargin: "Target Profit Margin (%)",
    marginNote: "The safety buffer. Net Profit target.",
    projectName: "Project Name",
    projectCode: "Project Code",
    projectManager: "Project Manager",
    projectCoordinator: "Project Coordinator",
    staffRateCard: "Staff Rate Card",
    name: "Name",
    role: "Role",
    baseRate: "Base Hourly Rate",
    location: "Location",
    loadedRate: "Loaded Rate",
    add: "Add",
    others: "Others",
    estimatesTitle: "Project Initial Estimates (Baseline)",
    laborBudget: "Labor / Hours Budget",
    expenseBudget: "Expenses / ODC Budget",
    estHours: "Est. Hours",
    estCost: "Est. Cost",
    addBudgetLine: "Add Estimate",
    totalEstCost: "Total Estimated Cost (BAC)",
    plannedProfit: "Planned Profit (Fee - Est. Cost)",
    varianceAnalysis: "Variance Analysis (Estimate vs Actual)",
    earnedValueTitle: "Earned Value Management (EVM)",
    progress: "Physical Progress (%)",
    ev: "Earned Value (EV)",
    cpi: "Cost Performance Index (CPI)",
    cpiDesc: "> 1.0 = Efficient (Under Budget)",
    evDesc: "Value of work performed (Cost Basis)",
    budgetVsActual: "Budget (BAC) vs Actual (AC)",
    hoursVariance: "Hours: Planned vs Actual",
    overBudget: "Over Budget",
    underBudget: "Under Budget",
    setBaselineFirst: "Please set up the estimates in the 'Estimates & Budget' tab to see EVM analysis.",
    aiCategorize: "Auto-Categorize",
    stoppageAnalysis: "Stoppage & Delay Analysis",
    stoppageDays: "Days Stopped/Delayed",
    stoppageCost: "Stoppage Cost (Passive Burn)",
    stoppageDesc: "Overhead leakage @ 40% of daily profit target",
    projectDuration: "Project Duration",
    startDate: "Start Date",
    endDate: "End Date",
    cpiDefinition: "Efficiency Indicator: Earned Value / Actual Cost (>1 Excellent)",
    projectStatus: "Project Status",
    statusActive: "Active",
    statusPaused: "Stopped / Paused",
    pausedSince: "Paused since:",
    pauseProject: "Stop Project",
    resumeProject: "Resume Project",
    daysCount: "Stoppage Days (Working Days)",
    manualAdj: "Manual Adj",
    periodFrom: "Period From",
    periodTo: "Period To",
    dateRange: "Date Range",
    paymentTitle: "Payments Schedule & Cash Flow",
    paymentDesc: "Track contract milestones, variation orders (VOs), and cash flow.",
    addPayment: "Add Payment / VO",
    payTitle: "Title / Milestone",
    payType: "Type",
    payAmount: "Amount",
    payDate: "Expected Date",
    payReq: "Requirements / Deliverables",
    payStatus: "Status",
    statusPending: "Pending",
    statusDue: "Due",
    statusClaimed: "Claim Issued",
    statusInvoiced: "Invoiced",
    statusPaidPartial: "Paid (Partial)",
    statusPaidFull: "Paid (Full)",
    typeContract: "Base Contract",
    typeVO: "Variation Order (VO)",
    totalInvoiced: "Total Invoiced",
    totalCollected: "Total Collected",
    financialCompletion: "Financial Completion %",
    outstanding: "Outstanding (Invoiced - Paid)",
    finCompDesc: "Based on Invoiced Amount / Total Contract Value",
    projects: "Projects",
    newProject: "New Project",
    loading: "Loading...",
    error: "Error occurred",
    success: "Success",
    noData: "No data available",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    percentComplete: "Percent Complete",
    marginPotential: "Margin Potential",
    signIn: "Sign In",
    signOut: "Sign Out",
    backToProjects: "Back to Projects",
    noProjects: "You haven't created any projects yet",
    designPMO: "Design PMO",
    subtitle: "Design Project Management & Control System",
  },
  ar: {
    dashboard: "لوحة التحكم",
    budgeting: "التقديرات الأولية",
    timeExpenses: "المصروفات الفعلية",
    payments: "الدفعات والتدفق النقدي",
    settings: "الإعدادات والأسعار",
    totalContractValue: "إجمالي قيمة العقد",
    approvedFee: "الأتعاب المعتمدة",
    totalBurn: "التكلفة الفعلية (AC)",
    includesOverhead: "شامل المصاريف الإدارية",
    remainingBudget: "الميزانية المتبقية",
    prodBudget: "ميزانية الإنتاج",
    currentMargin: "هامش الربح المتوقع",
    target: "المستهدف",
    budgetStatus: "حالة استهلاك الميزانية",
    utilized: "المستهلك",
    ofProdBudget: "من ميزانية الإنتاج",
    calcNote: "*محسوبة بناءً على صافي الإيرادات ناقص الربح المستهدف",
    costDist: "توزيع التكلفة (الرياض vs القاهرة)",
    riyadhMgmt: "الرياض (إدارة)",
    cairoProd: "القاهرة (إنتاج)",
    extExpenses: "مصروفات خارجية",
    criticalAlert: "تنبيه هام: اقتراب نفاد الميزانية",
    alertMsg: "لقد استهلكت {pct} من ميزانية الإنتاج. يتطلب اتخاذ إجراء فوري.",
    logHours: "سجل الساعات (Timesheet)",
    staffMember: "الموظف",
    selectResource: "اختر الموظف...",
    hoursSpent: "الساعات",
    phase: "المرحلة",
    phaseOther: "أخرى",
    description: "الوصف",
    taskDetail: "تفاصيل المهمة...",
    addTimeLog: "إضافة سجل ساعات",
    logExpenses: "سجل المصروفات (ODCs)",
    category: "البند / الفئة",
    amount: "المبلغ",
    reimbursable: "مستردة (على العميل)",
    addExpense: "إضافة مصروف",
    recentTrans: "آخر العمليات",
    type: "النوع",
    costType: "نوع التكلفة",
    action: "إجراء",
    labor: "عاملة",
    expense: "مصروف",
    loadedCost: "تكلفة محملة",
    directCost: "تكلفة مباشرة",
    noEntries: "لا توجد مدخلات حتى الآن.",
    projectParams: "المعايير المالية للمشروع",
    feeNote: "إجمالي الأتعاب الموقعة مع العميل (بدون ضريبة).",
    overhead: "معامل التحميل (Overhead)",
    overheadNote: "يضرب في الراتب الأساسي لتغطية الإيجار والإدارة.",
    targetMargin: "هامش الربح المستهدف (%)",
    marginNote: "صمام الأمان. صافي الربح المستهدف.",
    projectName: "اسم المشروع",
    projectCode: "كود المشروع",
    projectManager: "مدير المشروع",
    projectCoordinator: "منسق المشروع",
    staffRateCard: "بطاقة أسعار الفريق",
    name: "الاسم",
    role: "الدور",
    baseRate: "سعر الساعة الأساسي",
    location: "الموقع",
    loadedRate: "السعر المحمل",
    add: "إضافة",
    others: "أخرى",
    estimatesTitle: "التقديرات الأولية للمشروع (Baseline)",
    laborBudget: "موازنة الساعات / الفريق",
    expenseBudget: "موازنة المصروفات والعمولات",
    estHours: "ساعات مقدرة",
    estCost: "تكلفة مقدرة",
    addBudgetLine: "إضافة بند تقديري",
    totalEstCost: "إجمالي التكلفة المقدرة (BAC)",
    plannedProfit: "الربح المخطط (عند البداية)",
    varianceAnalysis: "تحليل الانحراف (المقدر vs الفعلي)",
    earnedValueTitle: "إدارة القيمة المكتسبة (EVM)",
    progress: "نسبة الإنجاز الفني (%)",
    ev: "القيمة المكتسبة (EV)",
    cpi: "مؤشر أداء التكلفة (CPI)",
    cpiDesc: "أعلى من 1.0 = كفاءة عالية",
    evDesc: "قيمة العمل المنجز (بناءً على التكلفة)",
    budgetVsActual: "الموازنة (BAC) مقابل الفعلي (AC)",
    hoursVariance: "انحراف الساعات: المقدر vs الفعلي",
    overBudget: "تجاوز الميزانية",
    underBudget: "وفر في الميزانية",
    setBaselineFirst: "يرجى تعبئة صفحة 'التقديرات والموازنة' أولاً لتفعيل تحليل القيمة المكتسبة.",
    aiCategorize: "تصنيف تلقائي",
    stoppageAnalysis: "تحليل التوقف والتأخير",
    stoppageDays: "أيام التوقف",
    stoppageCost: "تكلفة التوقف (الحرق السلبي)",
    stoppageDesc: "تسرب المصاريف الإدارية @ 40% من الربح اليومي",
    projectDuration: "مدة المشروع",
    startDate: "تاريخ البداية",
    endDate: "تاريخ النهاية",
    cpiDefinition: "مقياس الكفاءة: القيمة المنجزة ÷ التكلفة الفعلية (أعلى من 1 ممتاز)",
    projectStatus: "حالة المشروع",
    statusActive: "نشط",
    statusPaused: "متوقف / معلق",
    pausedSince: "تاريخ التوقف:",
    pauseProject: "إيقاف المشروع",
    resumeProject: "استئناف المشروع",
    daysCount: "عداد أيام التوقف (عمل فعلي)",
    manualAdj: "تعديل يدوي",
    periodFrom: "الفترة من",
    periodTo: "الفترة إلى",
    dateRange: "الفترة الزمنية",
    paymentTitle: "جدول الدفعات والتدفق النقدي",
    paymentDesc: "متابعة دفعات العقد، أوامر التغيير (VOs)، وحالة التحصيل.",
    addPayment: "إضافة دفعة / أمر تغيير",
    payTitle: "اسم الدفعة / المرحلة",
    payType: "النوع",
    payAmount: "القيمة",
    payDate: "تاريخ الاستحقاق",
    payReq: "المتطلبات / التسليمات",
    payStatus: "الحالة",
    statusPending: "مجدولة",
    statusDue: "مستحقة",
    statusClaimed: "تم إصدار المطالبة",
    statusInvoiced: "تمت الفوترة",
    statusPaidPartial: "تم السداد (جزئي)",
    statusPaidFull: "تم السداد (كلي)",
    typeContract: "عقد أساسي",
    typeVO: "أمر تغيير (VO)",
    totalInvoiced: "إجمالي المفوتر",
    totalCollected: "إجمالي المحصل",
    financialCompletion: "نسبة الإنجاز المالي",
    outstanding: "المستحقات (مفوتر - محصل)",
    finCompDesc: "بناءً على المفوتر ÷ إجمالي قيمة العقد",
    projects: "المشاريع",
    newProject: "مشروع جديد",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    success: "تم بنجاح",
    noData: "لا توجد بيانات",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    percentComplete: "نسبة الإنجاز",
    marginPotential: "إمكانية الربح",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    backToProjects: "العودة للمشاريع",
    noProjects: "لم تقم بإنشاء أي مشاريع بعد",
    designPMO: "Design PMO",
    subtitle: "نظام إدارة ومراقبة مشاريع التصميم",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('ar');
  const isRTL = lang === 'ar';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [lang, isRTL]);

  const toggleLanguage = () => {
    setLang(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
